version: '3.8'

services:
  bot:
    build:
      context: .
    container_name: image-resizer-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp  # Mount the temp directory for persistence
    ports:
      - "8443:8443"  # Assuming your bot listens on port 8443
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Ensure Redis port is exposed
    volumes:
      - redis_data:/data  # Use a named volume for Redis data persistence
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp  # Ensure worker also has access to temp
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

volumes:
  redis_data:
