services:
  bot:
    build:
      context: .
    container_name: image-resizer-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - FINAL_WIDTH=${FINAL_WIDTH}
      - FINAL_HEIGHT=${FINAL_HEIGHT}
      - ASPECT_RATIO_TOLERANCE=${ASPECT_RATIO_TOLERANCE}
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always
