services:
  bot:
    build:
      context: .
    container_name: image-resizer-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - FINAL_WIDTH=${FINAL_WIDTH}
      - FINAL_HEIGHT=${FINAL_HEIGHT}
      - ASPECT_RATIO_TOLERANCE=${ASPECT_RATIO_TOLERANCE}
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
