version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT:-"unknown"} # Передаём текущий коммит как аргумент сборки
    container_name: image-resizer-bot
    restart: unless-stopped
    env_file:
      - .env # Подключаем переменные окружения
    volumes:
      - ./temp:/app/temp # Локальная директория для временных файлов
    deploy:
      resources:
        limits:
          memory: 512m # Ограничиваем память
