services:
  bot:
    build: .
    container_name: image-resizer-bot
    env_file:
      - .env
    volumes:
      - temp:/app/temp
      - stats:/app/stats
    depends_on:
      - redis
      - worker
    restart: always

  worker:
    build: .
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    env_file:
      - .env
    volumes:
      - temp:/app/temp
      - stats:/app/stats
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

volumes:
  temp:
  stats:
