services:
  bot:
    build:
      context: .
    container_name: image-resizer-bot
    env_file:
      - .env
    volumes:
      - logs:/app/logs
      - temp:/app/temp
    ports:
      - "8443:8443"  # Adjust if your bot listens on a different port
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

  worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - logs:/app/logs
      - temp:/app/temp
    restart: always

volumes:
  redis_data:
  logs:
  temp: