version: '3.8'

services:
  bot:
    build:
      context: .
    container_name: image-resizer-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always

  worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256m
    restart: always
