name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "${{ secrets.PROJECT_PATH }}" ]; then
              echo "Cloning repository..."
              git clone https://github.com/akadorkin/image-resizer-bot.git ${{ secrets.PROJECT_PATH }}
            else
              echo "Repository exists. Pulling latest changes..."
              cd ${{ secrets.PROJECT_PATH }}
              git reset --hard
              git pull origin main
            fi
            cd ${{ secrets.PROJECT_PATH }}
            
            # Stop and remove old containers
            echo "Stopping old containers..."
            docker-compose down || true
            
            # Pull updated images
            echo "Pulling updated images..."
            docker-compose pull
            
            # Restart containers
            echo "Starting updated containers..."
            docker-compose up -d

